chinnuproject/chinnuproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chinnuproject/movieapp/urls.py
from django.urls import path
from. import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('register/',views.register,name='register'),
    path('add/',views.add,name='add'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),






]

chinnuproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    dep=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name
class Department(models.Model):
    name=models.CharField(max_length=250)
    course=models.TextField()
    def __str__(self):
        return self.name

chinnuproject/movieapp/forms.py
from django import forms
from.models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','dep','year']

chinnuproject/movieapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from.models import Movie,Department
from.forms import MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def login(request):

    if request.method =='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"invalid registation")

    return render(request,"login.html")
def register(request):

        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            cpassword = request.POST['password1']
            if password == cpassword:
                if User.objects.filter(username=username).exists():
                    messages.info(request, "Username Taken")

                else:
                    user = User.objects.create_user(username=username, password=password)
                    user.save();


            return redirect('/')
        return render(request, "register.html")
def add(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        dep =request.POST.get('dep',)
        year=request.POST.get('year',)

        movie=Movie(name=name,dep=dep,year=year)

        return redirect('/')
    return render(request,'add.html')
def logout(request):
    auth.logout(request)
    return redirect('/')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')

chinnuproject/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>form</h2>
<form method="POST" >
    {% csrf_token %}
    <input type="text" name="name"  placeholder="Enter your username">
   <p><b><a href="https:www.wikipedia.com">department</a>:</b>
       <select class="form-control"></a>
         <option value="1">computer science</option>
         <option value="2">commerce</option>
     </select>
   </p>


    <input type="text" name="year" placeholder="enter the year"><br>
    <input type="date" name="Date" placeholder="enter the date"><br>
    <input type="text" name="Age" placeholder="enter the age"><br>
    <input type="text" name="number" placeholder="enter the phone number"><br>
    <input type="text" name="mail" placeholder="enter the mail id"><br>
    <input type="text" name="address" placeholder="enter the address"><br>
    <input type="text" name="courses" placeholder="enter the courses"><br>
    <label>Gender</label><input type="radio">male<input type="radio">female<br>
    <input type="submit">
</form>
    <a class="btn btn-warning" href="{% url 'movieapp:logout' %}">Logout</a>
</body>
</html>

chinnuproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    Online school store
  </a>
    <a class="btn btn-warning" href="{% url 'movieapp:register' %}">Register</a>
    <a class="btn btn-warning" href="{% url 'movieapp:login' %}">Login</a>



<link rel="stylesheet" href="{% static 'style.css' %}">
    <div class="menu-bar">

    <ul>
        <li class="active"><a href="#"><i class="fa fa-user"></i>department</a>

            <div class="sub-menu-1">
                <ul>
                    <li><a href="https://en.wikipedia.org/wiki/Computer_science">Computer </a></li>
                     <li><a href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></li>
                    <li><a href="https://en.wikipedia.org/wiki/The_arts">Arts</a></li>
                </ul>
            </div>
        </li>

    </ul>
</div>


</nav>

{% block body %}
{% endblock %}
</body>
</html>

chinnuproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
 <div class="row">
  <div class="col-md-6">
   <img src="{{movie.img.url}}" width="200" height="200">

  </div>
  <div class="col-md-6">
   {{movie.name}}<br>
   {{movie.dep}}<br>
   {{movie.year}}<br>


  </div>




  </div>
</div>
{% endblock %}

chinnuproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">



  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>

  </div>
</div>
        </div>
        {% endfor %}



{% endblock %}

chinnuproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Login</h2>
<form action="login" method="post">
      {% csrf_token %}
       <input type="text" name="username" placeholder="enter your username"><br>
        <input type="password" name="password" placeholder="enter your password"><br>
        <input type="submit">

</form>
 <a class="btn btn-warning" href="{% url 'movieapp:add' %}">Form</a><br>
</body>
</html>

chinnuproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h2>Registration</h2>

<form method="POST" enctype="multipart/form-data">
    {%csrf_token %}

    <input type="text" name="username" placeholder="enter the username"><br>
    <input type="password" name="password" placeholder="enter the password"><br>
    <input type="password" name="password1" placeholder="enter confirm password"><br>
    <input type="submit">

</form>
</body>
</html>